# Start time: 2024-04-09 12:58:10.858014

'''
Prompt:
The prompt describes the relationship between the inputs and outputs. Given that the prompt is: ### Summary for Input Column Data:

The input column consists of full names of individuals, which are structured in a variety of formats. These names appear to include first names, middle initials, and last names, and in some cases, they might include cultural or regional variations in naming conventions. The names provided in the input column are diverse, indicating a range of backgrounds and possibly nationalities. The structure of these names suggests a standard naming convention in many English-speaking countries, where a person's given name is followed by a middle name or initial, and then their family name. However, the presence of names like "Ayako Tanaka" also hints at the inclusion of non-Western naming conventions, where the family name may precede the given name, or where middle names are less commonly used.

### Summary for Output Column Data:

The output column data consists of the first names extracted from the full names provided in the input column. This extraction process simplifies the identification of individuals by focusing solely on their given names. The output names are diverse, reflecting a range of cultural backgrounds. The simplification to first names indicates a standardization process, possibly aimed at facilitating easier communication or data processing where the specificity of full names is unnecessary. This column effectively distills the more complex input data into a more manageable form, focusing on the most commonly used part of a person's name in informal and some formal contexts.

### Relationship Between Input and Output:

The relationship between the input and output columns is characterized by a process of simplification and extraction. Specifically, the output is generated by isolating the first name from the full name provided in the input. This process demonstrates an understanding of naming conventions, where the first element of the input is typically the given name, which is of primary interest for the output. The transformation from input to output reflects a filtering of information to retain only the most immediately relevant piece (the first name) for the purposes at hand. This could be useful in scenarios where personalization or identification does not require the full complexity of a person's legal or formal name. The relationship underscores a practical approach to data management, where less can be more, and simplicity aids in clarity and utility., and input as ['Susan Ann Chang'] output is Susan, input as ['Ayako Tanaka'] output is Ayako, input as ['Bobby T. smth'] output is Bobby, , generate a python function that matches the given input and output above, treating the input and output as strings, not lists. If the input has multiple list elements, that means there are separate inputs that should be passed as separate arguments to the python function. Include the above input in test cases. Do not include the output of the test code in the python program. The generated python code should have only executable statements and comments. The function should return the output, not print it. Do not include assert statements. Name the generated python function as generated_function. Make sure to generate a python function as defined above.
'''

def generated_function(full_name):
    """
    Extracts the first name from a full name string.

    Parameters:
    full_name (str): A string containing the full name of an individual.

    Returns:
    str: The first name extracted from the full name.
    """
    # Split the full name by spaces to isolate individual components
    name_parts = full_name.split()
    # The first element in the list is assumed to be the first name
    first_name = name_parts[0]
    return first_name

# Test cases
print(generated_function('Susan Ann Chang'))  # Expected output: Susan
print(generated_function('Ayako Tanaka'))     # Expected output: Ayako
print(generated_function('Bobby T. smth'))    # Expected output: Bobby
print(generated_function("Susan Ann Chang"))  ## Output: Susan
print(generated_function("Ayako Tanaka"))  ## Output: Ayako
print(generated_function("Bobby T. smth"))  ## Output: Bobby

# End time: 2024-04-09 12:58:19.588515
# Elapsed time in seconds: 8.730332951000037


# APPEND TEST SCRIPTS...
print(generated_function("Susan Ann Chang"))  ## Output: Susan
print(generated_function("Ayako Tanaka"))  ## Output: Ayako
print(generated_function("Bobby T. smth"))  ## Output: Bobby


print(generated_function("Jackson Ann Turner"))  ### Output: Jackson
print(generated_function("Olivia Tanaka Parker"))  ### Output: Olivia
print(generated_function("Benjamin T. Hayes"))  ### Output: Benjamin

# TEST SCRIPTS APPENDED!

