# Start time: 2024-04-10 16:03:30.106838

'''
Prompt:
The prompt describes the relationship between the inputs and outputs. Given that the prompt is: Summary for Input Column Data:
- The input column data consists of names of individuals, with titles such as 'Nancy FreeHafer', 'Andrew Cencici', 'Jan Kotas', and 'Mariya Sergienko'.

Summary for Output Column:
- The output column consists of titles 'Dr. Nancy', 'Dr. Andrew', 'Dr. Jan', and 'Dr. Mariya'.

Relationship between Input and Output:
- The relationship between the input and output columns is that the input column contains full names of individuals, while the output column only includes the title 'Dr.' followed by the first name of the individual. This suggests that the output is generated by extracting the title 'Dr.' and the first name from the input data., and input as ['Nancy FreeHafer'] output is Dr. Nancy, input as ['Andrew Cencici'] output is Dr. Andrew, input as ['Jan Kotas'] output is Dr. Jan, input as ['Mariya Sergienko'] output is Dr. Mariya, , generate a python function that matches the given input and output above, treating the input and output as strings, not lists. If the input has multiple list elements, that means there are separate inputs that should be passed as separate arguments to the python function. Include the above input in test cases. Do not include the output of the test code in the python program. The generated python code should have only executable statements and comments. The function should return the output, not print it. Do not include assert statements. Name the generated python function as generated_function. Make sure to generate a python function as defined above.
'''

# Define the generated function
def generated_function(input_str):
    # Split the input string into first name and last name
    first_name = input_str.split()[0]
    # Generate the output string with 'Dr.' and the first name
    output_str = 'Dr. ' + first_name
    return output_str

# Test cases
print(generated_function('Nancy FreeHafer')) # Output: Dr. Nancy
print(generated_function('Andrew Cencici')) # Output: Dr. Andrew
print(generated_function('Jan Kotas')) # Output: Dr. Jan
print(generated_function('Mariya Sergienko')) # Output: Dr. Mariya
print(generated_function("Nancy FreeHafer"))  ## Output: Dr. Nancy
print(generated_function("Andrew Cencici"))  ## Output: Dr. Andrew
print(generated_function("Jan Kotas"))  ## Output: Dr. Jan
print(generated_function("Mariya Sergienko"))  ## Output: Dr. Mariya

# End time: 2024-04-10 16:03:31.820114
# Elapsed time in seconds: 1.7132267639999554