# Start time: 2024-04-10 15:12:26.856928

'''
Prompt:
The prompt describes the relationship between the inputs and outputs. Given that the prompt is: Summary for input column data:
- The first names in the input column data are 'ayako', 'amy', and 'tom'.
- The last names in the input column data are 'ogawa', 'johnson', and 'chang'.
- The domain names in the input column data are 'acme.com', 'google.com', and 'upenn.edu'.

Summary for output column data:
- The output column data consists of the first letter of the first name followed by the last name separated by an underscore, and then the domain name.

Relationship between input and output:
- The output is generated by taking the first letter of the first name, combining it with the last name separated by an underscore, and then adding the domain name.
- This relationship creates a unique identifier for each person based on their first and last names and the domain they are associated with., and input as ['ayako', 'ogawa', 'acme.com'] output is aogawa_acme.com, input as ['amy', 'johnson', 'google.com'] output is ajohnson_google.com, input as ['tom', 'chang', 'upenn.edu'] output is tchang_upenn.edu, , generate a python function that matches the given input and output above, treating the input and output as strings, not lists. If the input has multiple list elements, that means there are separate inputs that should be passed as separate arguments to the python function. Include the above input in test cases. Do not include the output of the test code in the python program. The generated python code should have only executable statements and comments. The function should return the output, not print it. Do not include assert statements. Name the generated python function as generated_function. Make sure to generate a python function as defined above.
'''

# Define the python function
def generated_function(first_name, last_name, domain):
    # Combine the first letter of the first name, last name separated by an underscore, and the domain name
    output = first_name[0] + last_name + '_' + domain
    return output

# Test cases
print(generated_function('ayako', 'ogawa', 'acme.com'))  # Output: aogawa_acme.com
print(generated_function('amy', 'johnson', 'google.com'))  # Output: ajohnson_google.com
print(generated_function('tom', 'chang', 'upenn.edu'))  # Output: tchang_upenn.edu
print(generated_function("ayako", "ogawa", "acme.com"))  ## Output: aogawa_acme.com
print(generated_function("amy", "johnson", "google.com"))  ## Output: ajohnson_google.com
print(generated_function("tom", "chang", "upenn.edu"))  ## Output: tchang_upenn.edu

# End time: 2024-04-10 15:12:28.903027
# Elapsed time in seconds: 2.0460517589999654