# Start time: 2024-04-10 15:38:19.366791

'''
Prompt:
The prompt describes the relationship between the inputs and outputs. Given that the prompt is: Summary for Input Column Data:
- The input column data consists of full names of individuals.
- Each full name is in the format of 'First Name Last Name'.
- The names in the input column data are diverse and do not follow a specific pattern.

Summary for Output Column Data:
- The output column data consists of initials derived from the input full names.
- The initials are in the format of 'First Initial.Last Initial'.
- The output column data provides a concise representation of the input full names.

Relationship between Input and Output:
- The output column data is generated by taking the first initial of the first name and the first initial of the last name from the input column data.
- The relationship between the input and output is that the output provides a shortened version of the input full names.
- The output column data serves as a simplified and standardized representation of the input column data, making it easier to identify individuals., and input as ['Nancy FreeHafer'] output is N.F., input as ['Andrew Cencici'] output is A.C., input as ['Jan Kotas'] output is J.K., input as ['Mariya Sergienko'] output is M.S., , generate a python function that matches the given input and output above, treating the input and output as strings, not lists. If the input has multiple list elements, that means there are separate inputs that should be passed as separate arguments to the python function. Include the above input in test cases. Do not include the output of the test code in the python program. The generated python code should have only executable statements and comments. The function should return the output, not print it. Do not include assert statements. Name the generated python function as generated_function. Make sure to generate a python function as defined above.
'''

def generated_function(input_str):
    # Split the input full name into first name and last name
    full_name = input_str.split()
    first_name = full_name[0]
    last_name = full_name[1]
    
    # Get the first initial of the first name and last name
    first_initial = first_name[0]
    last_initial = last_name[0]
    
    # Combine the initials into the output format
    output = first_initial + '.' + last_initial
    
    return output

# Test cases
print(generated_function('Nancy FreeHafer'))
print(generated_function('Andrew Cencici'))
print(generated_function('Jan Kotas'))
print(generated_function('Mariya Sergienko'))
print(generated_function("Nancy FreeHafer"))  ## Output: N.F.
print(generated_function("Andrew Cencici"))  ## Output: A.C.
print(generated_function("Jan Kotas"))  ## Output: J.K.
print(generated_function("Mariya Sergienko"))  ## Output: M.S.

# End time: 2024-04-10 15:38:21.561112
# Elapsed time in seconds: 2.1942686630000026